arch:
- amd64
- aarch64
- armhf
- armv7
boot: auto
description: onewire server to read 1-Wire devices
image: ghcr.io/lrybak/owserver/{arch}
ingress: true
init: false
name: owserver (1-wire)
options:
  owhttpd: true
  temperature_scale: Celsius
panel_icon: mdi:alpha-w-box
schema:
  debug: bool?
  device: device
  device_type: list(serial_or_i2c|usb|fake)
  owhttpd: bool
  temperature_scale: list(Celsius|Fahrenheit|Kelvin|Rankine)
slug: owserver
startup: system
uart: true
url: https://github.com/lrybak/hassio-owserver
version: 3594e6b
