---
name: owserver
version: dev
slug: owserver
description: onewire server to read 1-Wire devices
url: https://github.com/lrybak/addon-owserver
startup: system
init: false
arch: 
  - amd64
boot: auto  
auto_uart: true
options:
  owhttpd: true
  device: ""
schema:
  owhttpd: bool
  device: str?
ingress: true
panel_icon: mdi:alpha-w-box
