arch:
- amd64
- aarch64
- armhf
- armv7
auto_uart: true
boot: auto
description: onewire server to read 1-Wire devices
image: ghcr.io/lrybak/owserver/{arch}
ingress: true
init: false
name: owserver (1-wire)
options:
  device: ''
  owhttpd: true
panel_icon: mdi:alpha-w-box
schema:
  device: str?
  owhttpd: bool
slug: owserver
startup: system
url: https://github.com/lrybak/addon-owserver
version: 0.3.0
